"""initial schema

TerraForge 数据库迁移（Alembic 自动生成，按需手工微调）

Revision ID: 0001
Revises: 
Create Date: 2026-08-06 20:27:23.992278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tf_conversation',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('project_name', sa.String(length=256), nullable=True, comment='工程项目名'),
    sa.Column('project_type', sa.String(length=64), nullable=True, comment='工程类型 房建/市政/桥梁'),
    sa.Column('discipline', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True, comment='地区，影响地标适用'),
    sa.Column('kb_ids', sa.JSON(), nullable=True, comment='本会话检索范围'),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tf_conversation_user_id'), ['user_id'], unique=False)

    op.create_table('tf_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True, comment='1=有帮助 -1=没帮助'),
    sa.Column('reason', sa.String(length=64), nullable=True, comment='not_found/wrong/outdated/incomplete'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tf_feedback_message_id'), ['message_id'], unique=False)

    op.create_table('tf_governance_task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False, comment='expire_check/duplicate_merge/gap_fill/conflict_resolve'),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_doc_ids', sa.JSON(), nullable=True),
    sa.Column('kb_id', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True, comment='high/medium/low'),
    sa.Column('status', sa.String(length=16), nullable=True, comment='open/processing/done/closed'),
    sa.Column('assignee', sa.String(length=64), nullable=True, comment='维护负责人'),
    sa.Column('watchers', sa.JSON(), nullable=True, comment='关注人'),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_governance_task', schema=None) as batch_op:
        batch_op.create_index('idx_gov_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tf_governance_task_kb_id'), ['kb_id'], unique=False)

    op.create_table('tf_knowledge_base',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='知识库名称'),
    sa.Column('domain', sa.String(length=32), nullable=False, comment='知识域: standard/case/enterprise'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True, comment='维护负责人'),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_knowledge_base', schema=None) as batch_op:
        batch_op.create_index('idx_kb_domain', ['domain'], unique=False)

    op.create_table('tf_query_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True, comment='召回数量'),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=True, comment='是否给出有依据的答案'),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_query_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tf_query_log_created_at'), ['created_at'], unique=False)

    op.create_table('tf_document',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kb_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='内容SHA256，用于去重'),
    sa.Column('standard_code', sa.String(length=64), nullable=True, comment='规范编号 如 GB50204-2015'),
    sa.Column('standard_name', sa.String(length=256), nullable=True, comment='规范名称'),
    sa.Column('discipline', sa.String(length=32), nullable=True, comment='专业分部'),
    sa.Column('project_name', sa.String(length=256), nullable=True, comment='所属项目'),
    sa.Column('effective_date', sa.DateTime(), nullable=True, comment='实施日期'),
    sa.Column('expire_date', sa.DateTime(), nullable=True, comment='废止日期'),
    sa.Column('governance_status', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True, comment='文档负责人'),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['tf_knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_document', schema=None) as batch_op:
        batch_op.create_index('idx_doc_hash', ['file_hash'], unique=False)
        batch_op.create_index('idx_doc_kb', ['kb_id'], unique=False)
        batch_op.create_index('idx_doc_status', ['status'], unique=False)
        batch_op.create_index('idx_doc_std_code', ['standard_code'], unique=False)

    op.create_table('tf_message',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False, comment='user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=16), nullable=True),
    sa.Column('need_human_review', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('stage_trace', sa.JSON(), nullable=True, comment='Stage0-7 各阶段耗时与产出摘要'),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['tf_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_message', schema=None) as batch_op:
        batch_op.create_index('idx_msg_conv', ['conversation_id'], unique=False)

    op.create_table('tf_chunk',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('doc_id', sa.String(length=32), nullable=False),
    sa.Column('kb_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True, comment='文档内顺序'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.String(length=512), nullable=True, comment='章节路径 如 5.2.1 混凝土养护'),
    sa.Column('clause_no', sa.String(length=64), nullable=True, comment='条文号'),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.String(length=32), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True, comment='是否强制性条文'),
    sa.Column('vector_id', sa.String(length=64), nullable=True, comment='向量库主键'),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['tf_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_chunk', schema=None) as batch_op:
        batch_op.create_index('idx_chunk_doc', ['doc_id'], unique=False)
        batch_op.create_index('idx_chunk_domain', ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_tf_chunk_kb_id'), ['kb_id'], unique=False)

    op.create_table('tf_citation',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('index_no', sa.Integer(), nullable=True, comment='答案中的角标序号 [1]'),
    sa.Column('chunk_id', sa.String(length=32), nullable=True),
    sa.Column('doc_id', sa.String(length=32), nullable=True),
    sa.Column('doc_title', sa.String(length=256), nullable=True),
    sa.Column('standard_code', sa.String(length=64), nullable=True),
    sa.Column('section_path', sa.String(length=512), nullable=True),
    sa.Column('clause_no', sa.String(length=64), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['tf_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tf_citation', schema=None) as batch_op:
        batch_op.create_index('idx_cite_msg', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tf_citation', schema=None) as batch_op:
        batch_op.drop_index('idx_cite_msg')

    op.drop_table('tf_citation')
    with op.batch_alter_table('tf_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tf_chunk_kb_id'))
        batch_op.drop_index('idx_chunk_domain')
        batch_op.drop_index('idx_chunk_doc')

    op.drop_table('tf_chunk')
    with op.batch_alter_table('tf_message', schema=None) as batch_op:
        batch_op.drop_index('idx_msg_conv')

    op.drop_table('tf_message')
    with op.batch_alter_table('tf_document', schema=None) as batch_op:
        batch_op.drop_index('idx_doc_std_code')
        batch_op.drop_index('idx_doc_status')
        batch_op.drop_index('idx_doc_kb')
        batch_op.drop_index('idx_doc_hash')

    op.drop_table('tf_document')
    with op.batch_alter_table('tf_query_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tf_query_log_created_at'))

    op.drop_table('tf_query_log')
    with op.batch_alter_table('tf_knowledge_base', schema=None) as batch_op:
        batch_op.drop_index('idx_kb_domain')

    op.drop_table('tf_knowledge_base')
    with op.batch_alter_table('tf_governance_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tf_governance_task_kb_id'))
        batch_op.drop_index('idx_gov_status')

    op.drop_table('tf_governance_task')
    with op.batch_alter_table('tf_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tf_feedback_message_id'))

    op.drop_table('tf_feedback')
    with op.batch_alter_table('tf_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tf_conversation_user_id'))

    op.drop_table('tf_conversation')
    # ### end Alembic commands ###
